plugins{
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'org.spongepowered.mixin' version '0.7+'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = minecraft_version + '-' + mod_version
group = 'net.smileycorp.bloodsmeltery'

base{
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))
minecraft {
    mappings channel: mapping_channel, version: mapping_version

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg') // Currently, this location cannot be changed from the default.
    copyIdeResources = true

    runs {
        configureEach {
//            properties 'mixin.env.disableRefMap': 'true'

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }

        }
        client {
            workingDirectory project.file('run')
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            workingDirectory project.file('run-server')
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "bloodsmeltery.refmap.json"
    config "bloodsmeltry.mixins.json"
}

repositories {
    maven {
        name = "The Loader"
        url = "https://maven.blamejared.com"
    }
    maven {
        // Curios
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        // Mystical Agriculture, Cucumber (library)
        url = "https://maven.blakesmods.com/"
    }
    maven {
        url = "https://cursemaven.com/"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras}")) {
        jarJar.ranged(it, "[${mixin_extras},)")
    }

    implementation fg.deobf("curse.maven:blood-magic-224791:7253333")

    implementation fg.deobf("slimeknights.mantle:Mantle:${minecraft_version}-${mantle_version}")
    Implementation("slimeknights.tconstruct:TConstruct:${minecraft_version}-${tconstruct_version}")

    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    compileOnly fg.deobf("vazkii.patchouli:Patchouli:${patchouli_version}:api")
    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:${patchouli_version}")

    compileOnly fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}-${create_version_number}:slim")
    runtimeOnly fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}-${create_version_number}:slim")

    compileOnly("dev.engine-room.flywheel:flywheel-forge-api-${flywheel_minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-forge-${flywheel_minecraft_version}:${flywheel_version}")


	//implementation fg.deobf('curse.maven:cofhcore-69162:4385215')
	//implementation fg.deobf('curse.maven:thermalfoundation-222880:4382339')
	//implementation fg.deobf('curse.maven:thermalexpansion-69163:4382343')
	//implementation fg.deobf('curse.maven:thermaldynamics-227443:4391159')
	//implementation fg.deobf('curse.maven:thermalintegration-626708:4382885')
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
				"Specification-Title"     :"Blood-Smeltery",
				"Specification-Vendor"    :"smileycorp",
				"Specification-Version"   :"1", // We are version 1 of ourselves
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : project.jar.archiveVersion,
				"Implementation-Vendor"   :"smileycorp",
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
				"TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
				"TweakOrder": 0,
				"MixinConfigs": "bloodsmeltery.mixin.json"
        ])
    }
}

// Example configuration to allow publishing using the maven-publish plugin
// This is the preferred method to reobfuscate your jar file
tasks.named('jarJar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     :"Blood-Smeltery",
				"Specification-Vendor"    :"smileycorp",
				"Specification-Version"   :"1", // We are version 1 of ourselves
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : project.jar.archiveVersion,
				"Implementation-Vendor"   :"smileycorp",
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
				"TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
				"TweakOrder": 0,
				"MixinConfigs": "bloodsmeltery.mixin.json"
        ])
    }
    archiveClassifier = ''
    finalizedBy 'reobfJarJar'
}
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing
// publish.dependsOn('reobfJar')

task srcJar(type: Jar) {
    from(sourceSets.main.java)
    archiveClassifier = 'sources'
}

task apiJar(type: Jar) {
    from(sourceSets.main.allJava)
    from(sourceSets.main.output)
    include 'wayoftime/bloodmagic/api/**'

    archiveClassifier = 'api'
}

artifacts {
    archives srcJar, apiJar
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            jarJar.component(it)
            artifact jar
            artifact srcJar
            artifact apiJar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
